retreats = [
    {
        "title": "Yoga for Stress Relief",
        "description": "A weekend retreat focused on yoga and meditation to relieve stress.",
        "date": "25-08-2023 00:00:00",
        "location": "Goa",
        "price": 200,
        "type": "Signature",
        "condition": "Stress Relief",
        "image": "https://cdn.mjourney.com/a287f9bc-d0fb-4e78-a0fa-e8136d3c408a/0_0.jpeg",
        "tag": ["relaxation", "meditation", "weekend"],
        "duration": 3,
    },
    {
        "title": "Flexibility Improvement Workshop",
        "description": "A 5-day workshop designed to improve flexibility through yoga.",
        "date": "10-09-2023 00:00:00",
        "location": "Rishikesh",
        "price": 500,
        "type": "Standalone",
        "condition": "Flexibility Improvement",
        "image": "https://cdn.mjourney.com/4eef5d57-1601-4b80-8e82-523003e9f95d/0_0.jpeg",
        "tag": ["flexibility", "yoga", "workshop"],
        "duration": 5,
    },
    {
        "title": "Weight Loss Retreat",
        "description": "A 7-day retreat focused on weight loss through yoga and diet.",
        "date": "01-10-2023 00:00:00",
        "location": "Kerala",
        "price": 700,
        "type": "Signature",
        "condition": "Weight Loss",
        "image": "https://cdn.mjourney.com/bc82ebc6-a3a4-4eda-be0b-bb3e65d4b8d3/0_1.jpeg",
        "tag": ["weight loss", "diet", "yoga"],
        "duration": 7,
    },
    {
        "title": "General Fitness Yoga Camp",
        "description": "A 3-day yoga camp to enhance overall fitness and well-being.",
        "date": "15-09-2023 00:00:00",
        "location": "Mumbai",
        "price": 300,
        "type": "Standalone",
        "condition": "General Fitness",
        "image": "https://cdn.mjourney.com/930ec767-aa6d-46e6-92a6-f019a9718304/0_3.jpeg",
        "tag": ["fitness", "yoga", "camp"],
        "duration": 3,
    },
    {
        "title": "Chronic Pain Management",
        "description": "A weekend retreat to manage chronic pain through specialized yoga techniques.",
        "date": "20-11-2023 00:00:00",
        "location": "Delhi",
        "price": 250,
        "type": "Signature",
        "condition": "Chronic Pain Management",
        "image": "https://cdn.mjourney.com/5b0cec06-2f37-4828-8602-316f6dbd0eb6/0_0.jpeg",
        "tag": ["pain management", "yoga", "weekend"],
        "duration": 2,
    },
    {
        "title": "Mental Wellness Retreat",
        "description": "A 4-day retreat focused on mental wellness through yoga and meditation.",
        "date": "05-12-2023 00:00:00",
        "location": "Pune",
        "price": 400,
        "type": "Standalone",
        "condition": "Mental Wellness",
        "image": "https://cdn.mjourney.com/32923aeb-db8c-4c27-8e9d-fb82928b7fc1/0_2.jpeg",
        "tag": ["mental wellness", "meditation", "yoga"],
        "duration": 4,
    },
    {
        "title": "Pre/Post-Natal Yoga",
        "description": "A specialized yoga program for pre and post-natal women.",
        "date": "05-09-2023 00:00:00",
        "location": "Chennai",
        "price": 350,
        "type": "Standalone",
        "condition": "Pre/Post-Natal",
        "image": "https://cdn.mjourney.com/1bf1a655-289a-48e4-a156-0dde0cf1b7ce/0_1.jpeg",
        "tag": ["pre-natal", "post-natal", "yoga"],
        "duration": 3,
    },
    {
        "title": "Detox Retreat",
        "description": "A 5-day detox retreat to cleanse the body and mind.",
        "date": "10-11-2023 00:00:00",
        "location": "Hyderabad",
        "price": 550,
        "type": "Signature",
        "condition": "Detox",
        "image": "https://cdn.mjourney.com/873b60f7-f026-40f9-b2d7-184e981ee1f5/0_3.jpeg",
        "tag": ["detox", "cleanse", "yoga"],
        "duration": 5,
    },
    {
        "title": "Spiritual Growth Retreat",
        "description": "A 7-day retreat focusing on spiritual growth through yoga and meditation.",
        "date": "15-12-2023 00:00:00",
        "location": "Varanasi",
        "price": 800,
        "type": "Signature",
        "condition": "Spiritual Growth",
        "image": "https://cdn.mjourney.com/e0dba42d-84bc-45e6-acca-bbaf8f817371/0_1.jpeg",
        "tag": ["spiritual growth", "meditation", "yoga"],
        "duration": 7,
    },
    {
        "title": "General Fitness Yoga Camp",
        "description": "A 3-day yoga camp to enhance overall fitness and well-being.",
        "date": "20-09-2023 00:00:00",
        "location": "Kolkata",
        "price": 350,
        "type": "Standalone",
        "condition": "General Fitness",
        "image": "https://cdn.mjourney.com/5d5f32ef-c40a-4258-9856-85db2f4f943a/0_0.jpeg",
        "tag": ["fitness", "yoga", "camp"],
        "duration": 3,
    },
    {
        "title": "Yoga Event 11",
        "description": "A description for Yoga Event 11.",
        "date": "13-08-2024 16:34:40",
        "location": "Pune",
        "price": 704,
        "type": "Signature",
        "condition": "Chronic Pain Management",
        "image": "https://cdn.mjourney.com/ec4680e8-d074-4a69-a24b-3d3f3946907b/0_2.jpeg",
        "tag": ["yoga", "camp", "weekend"],
        "duration": 10,
    },
    {
        "title": "Yoga Event 12",
        "description": "A description for Yoga Event 12.",
        "date": "07-09-2024 03:03:04",
        "location": "Chennai",
        "price": 376,
        "type": "Signature",
        "condition": "Chronic Pain Management",
        "image": "https://cdn.mjourney.com/02d7f36d-ba93-4850-b555-3ede5a22eca8/0_0.jpeg",
        "tag": ["diet", "meditation", "pain management"],
        "duration": 7,
    },
    {
        "title": "Yoga Event 13",
        "description": "A description for Yoga Event 13.",
        "date": "21-12-2024 01:49:42",
        "location": "Delhi",
        "price": 737,
        "type": "Signature",
        "condition": "Detox",
        "image": "https://cdn.mjourney.com/6eb2d2b3-eb07-427a-89f1-b5ac2df1c8f1/0_2.jpeg",
        "tag": ["pain management", "meditation", "relaxation"],
        "duration": 4,
    },
    {
        "title": "Yoga Event 14",
        "description": "A description for Yoga Event 14.",
        "date": "13-12-2024 02:22:41",
        "location": "Chennai",
        "price": 107,
        "type": "Standalone",
        "condition": "Mental Wellness",
        "image": "https://cdn.mjourney.com/e6c8452a-af8e-4cd3-b15a-c3dcf2a696a5/0_3.jpeg",
        "tag": ["workshop", "weight loss", "meditation"],
        "duration": 7,
    },
    {
        "title": "Yoga Event 15",
        "description": "A description for Yoga Event 15.",
        "date": "26-10-2024 10:51:48",
        "location": "Rishikesh",
        "price": 882,
        "type": "Signature",
        "condition": "Detox",
        "image": "https://cdn.mjourney.com/30ee2214-0810-4e17-aa5e-0c2edc1b4354/0_0.jpeg",
        "tag": ["spiritual growth", "diet", "weekend"],
        "duration": 10,
    },
    {
        "title": "Yoga Event 16",
        "description": "A description for Yoga Event 16.",
        "date": "04-09-2024 17:54:11",
        "location": "Delhi",
        "price": 311,
        "type": "Signature",
        "condition": "Flexibility Improvement",
        "image": "https://cdn.mjourney.com/2f9daef3-406b-4266-835e-a07fb09b4820/0_0.jpeg",
        "tag": ["relaxation", "spiritual growth", "flexibility"],
        "duration": 3,
    },
    {
        "title": "Yoga Event 17",
        "description": "A description for Yoga Event 17.",
        "date": "23-12-2024 16:50:58",
        "location": "Goa",
        "price": 555,
        "type": "Standalone",
        "condition": "Mental Wellness",
        "image": "https://cdn.mjourney.com/2f72aafd-e2f2-4bec-8afc-80877aa4634f/0_0.jpeg",
        "tag": ["yoga", "camp", "weekend"],
        "duration": 6,
    },
    {
        "description": "A description for Yoga Event 18.",
        "date": "29-09-2024 16:55:42",
        "location": "Goa",
        "price": 414,
        "type": "Standalone",
        "condition": "Stress Relief",
        "image": "https://cdn.mjourney.com/873b60f7-f026-40f9-b2d7-184e981ee1f5/0_3.jpeg",
        "tag": ["weight loss", "workshop", "pain management"],
        "duration": 2,
    },
    {
        "title": "Yoga Event 19",
        "description": "A description for Yoga Event 19.",
        "date": "22-11-2024 06:04:14",
        "location": "Rishikesh",
        "price": 219,
        "type": "Standalone",
        "condition": "Mental Wellness",
        "image": "https://cdn.mjourney.com/e0dba42d-84bc-45e6-acca-bbaf8f817371/0_1.jpeg",
        "tag": ["diet", "weekend", "flexibility"],
        "duration": 7,
    },
    {
        "title": "Yoga Event 20",
        "description": "A description for Yoga Event 20.",
        "date": "06-09-2024 00:18:22",
        "location": "Varanasi",
        "price": 142,
        "type": "Signature",
        "condition": "Stress Relief",
        "image": "https://cdn.mjourney.com/5d5f32ef-c40a-4258-9856-85db2f4f943a/0_0.jpeg",
        "tag": ["weight loss", "camp", "yoga"],
        "duration": 2,
    },
    {
        "title": "Prachi Yoga  Event in pune Organised by usman please visit here",
        "description": "when you will visit i'll tell the description.",
        "date": "06-09-2024 00:18:22",
        "location": "pune",
        "price": 101,
        "type": "Signature",
        "condition": "Stress Relief",
        "image": "https://images.pexels.com/photos/802417/pexels-photo-802417.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "tag": ["weight loss", "camp", "yoga"],
        "duration": 3,
    },
    {
        "title": "Prashant Yoga  Event in Agra Organised by vishal please visit here",
        "description": "Organized by Vishal, this event invites you to experience the profound benefits of yoga in the beautiful city of Agra. Join us for a rejuvenating session that aims to harmonize mind, body, and spirit.",
        "date": "13-08-2024 20:38:22",
        "location": "Agra",
        "price": 101,
        "type": "Signature",
        "condition": "Stress Relief",
        "image": "https://images.pexels.com/photos/4078093/pexels-photo-4078093.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "tag": ["weight loss", "camp", "meditation"],
        "duration": 5,
    },
]
